version: 2
updates:
  - package-ecosystem: npm
    directory: "/back"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/front"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/back"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/front"
    schedule:
      interval: weekly
