version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pin-my-map-mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pinmymap
      - MONGO_INITDB_ROOT_PASSWORD=pinmymap

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: build
    container_name: pin-my-map-backend
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://pinmymap:pinmymap@mongodb:27017/pinmymap?authSource=admin
      - JWT_SECRET=dev_secret_key
      - PORT=8080
    depends_on:
      - mongodb
    command: yarn start:dev

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: build
    container_name: pin-my-map-frontend
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PUBLIC_API_BASE_URL=http://localhost:8080
      - PUBLIC_MAPBOX_ACCESS_TOKEN=your_mapbox_token
    depends_on:
      - backend
    command: yarn dev --host 0.0.0.0

volumes:
  mongodb_data: